baseURL = "https://tecnotrol.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Tecnotrol"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
[[menu.main]]
URL = "http:asd.com"
name = "asd"
weight = "22"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "By Federico Santana, template from Themefisher"
description = "This is meta description"
footer_content = "Desde la Patagonia con 20 años de experiencia proveemos soluciones en generación de energías renovables, automatización, instrumentación y control industrial."
footer_menu_left = "Nosotros"
footer_menu_middle = "Productos"
footer_menu_right = "Algo más"
logo = "images/logo.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/tecnotrol/"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#https://twitter.com/Tecnotrol"
title = "twitter"
[[params.social]]
icon = "ti-skype"
link = "#"
title = "skype"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
